export interface EngineRoomTerm {
  id: string;
  name: string;
  short: string;
  rawCat: string;
  icon: string;
  color: string;
  status: 'running' | 'standby' | 'maintenance' | 'alarm';
  shortDesc: string;
  purpose: string;
  role: string;
  importance: string;
  technical: string;
  components: string[];
  watchkeeping: string[];
}

export const engineRoomTerms: EngineRoomTerm[] = [
  {
    id: 'main-engine', name: 'Main Engine', short: 'MAN B&W 6S80ME-C10.5', rawCat: 'Propulsion', icon: '🟢', color: '#ea7018', status: 'running',
    shortDesc: 'Primary propulsion — 2-stroke turbocharged slow-speed diesel directly coupled to the fixed-pitch propeller.',
    purpose: 'The main engine converts the chemical energy stored in heavy fuel oil (HFO) into mechanical rotary motion, transmitted via the shafting system to drive the propeller and move the vessel through water. It is the heart of the propulsion plant and the largest single consumer of energy aboard.',
    role: 'Runs continuously at sea, directly coupled to the propeller shaft without a gearbox. Controlled from the ECR or bridge manoeuvring console. Operates on HFO at sea and switches to low-sulphur MDO/MGO on entering Emission Control Areas (ECAs) as mandated by MARPOL Annex VI Regulation 14.',
    importance: 'Loss of main engine propulsion is a Category A emergency. It accounts for 75–80% of total fuel consumption; its thermal efficiency directly determines voyage economics, emissions compliance with IMO Tier II/III limits, and the vessel\'s commercial competitiveness.',
    technical: 'A uniflow-scavenged, two-stroke, crosshead, direct reversible diesel. Combustion drives the piston down; force passes through the piston rod to the crosshead, then via the connecting rod to the crankshaft. Charge air is compressed by the exhaust-driven turbocharger and cooled in the scavenge air cooler before entering the cylinder.',
    components: ['Cylinder liner, jacket & cooling water passages', 'Piston, piston rod, piston rings & crown', 'Crosshead bearing & guide shoes', 'Connecting rod & crankshaft', 'Cylinder head & hydraulic exhaust valve', 'Fuel injection pump & injector (HPS or ME-GI)', 'Turbocharger (MET or TCA series)', 'Scavenge air cooler (charge air cooler)', 'Bedplate & main bearings', 'ME Control System — MCC, ECU, ACU per cylinder', 'Oil mist detector (OMD) & crankcase ventilation'],
    watchkeeping: ['Exhaust gas temperature per cylinder — max 420–450 °C; investigate deviation from mean', 'Scavenge air pressure — 2.6–3.2 bar depending on load', 'Jacket cooling water outlet temperature — 78–88 °C', 'Lube oil inlet pressure — minimum 2.8 bar; temperature 43–48 °C', 'Turbocharger RPM and exhaust gas inlet temperature', 'Crankcase OMD reading — investigate any rise immediately; stop engine if alarm', 'Thrust bearing temperature — maximum 65 °C', 'Scavenge space inspection — no oil accumulation, no water']
  },
  {
    id: 'aux-engine', name: 'Aux Engine / D.G.', short: 'Wärtsilä 9L32 — 3,240 kW', rawCat: 'Power Generation', icon: '⚡', color: '#2a8fd4', status: 'running',
    shortDesc: '4-stroke medium-speed diesel generator supplying 6.6 kV electrical power for all vessel services.',
    purpose: 'The diesel generator (DG) set produces all electrical power for the vessel: propulsion auxiliaries, pumps, deck machinery, navigation and communication systems, accommodation, refrigeration, and all automation and safety systems.',
    role: 'Two generators run in parallel at sea for redundancy; a third is on hot standby with auto-start armed. Load sharing is managed by governor load sharing controllers (LSC). The IAS monitors total demand and starts or stops units accordingly.',
    importance: 'A total blackout simultaneously disables propulsion controls, steering, navigation, communication and fire pumps — the most dangerous single failure scenario at sea. SOLAS mandates an independent emergency generator.',
    technical: 'A four-stroke, trunk-piston, turbocharged, intercooled, medium-speed diesel running at constant 750 RPM to maintain 60 Hz frequency. A hydraulic governor controls fuel delivery. The brushless synchronous alternator\'s AVR adjusts field excitation to hold 6,600 V ±5%.',
    components: ['9-cylinder in-line engine block & frame', 'Turbocharger & charge air intercooler', 'Woodward hydraulic governor', 'Brushless synchronous alternator', 'AVR (Automatic Voltage Regulator)', 'Air Circuit Breaker (ACB)', 'Synchroscope & auto-synchroniser', 'Load sharing controller (LSC)', 'Starting air system (25–30 bar per engine)', 'Jacket cooling water pre-heater'],
    watchkeeping: ['Generator output — kW and kVAR; monitor power factor (~0.8 lag)', 'Voltage 6,600 V ±5%; Frequency 60 Hz ±2.5%', 'Exhaust gas temperature per cylinder — monitor deviations', 'LO pressure min 3.5 bar; outlet temperature max 90 °C', 'Alternator winding temperature — maximum 130 °C (Class F)', 'Earth fault indication on main switchboard', 'Load sharing balance between parallel running generators', 'Starting air pressure — maintain minimum 25 bar at all times']
  },
  {
    id: 'boiler', name: 'Auxiliary Boiler', short: 'Aalborg Composite EGB / Oil-fired', rawCat: 'Heat & Steam', icon: '🔥', color: '#dc3545', status: 'running',
    shortDesc: 'Composite exhaust gas / oil-fired boiler producing 7 bar saturated steam for fuel heating and services.',
    purpose: 'Produces saturated steam at 7 bar for heavy fuel oil heating (HFO must reach 130–150 °C for correct viscosity), accommodation heating, fresh water distillation, and cargo heating on tankers.',
    role: 'At sea, operates in EGB mode — recovering waste heat from the main engine exhaust at zero fuel cost. Switches to oil-fired mode in port or when steam demand exceeds exhaust recovery. Feed water is automatically controlled to maintain drum level at mid-glass.',
    importance: 'Without steam heating, HFO viscosity rises beyond the limits of injection pumps and injectors. Loss of boiler feed water — an empty drum — is a critical emergency causing immediate tube failure and boiler damage.',
    technical: 'Two heat-input sections share a common steam drum. The EGB tube bank sits in the ME exhaust uptake — hot exhaust (300–350 °C) heats water inside the tubes. The oil-fired section has pressure-atomising burners firing into a refractory-lined furnace.',
    components: ['Steam drum (with cyclone separators and chevron driers)', 'EGB tube bank in ME exhaust uptake', 'Oil burner(s) & pressure atomiser', 'Automatic feed water control valve', 'Safety valves ×2 — set at 8.5 bar', 'Gauge glasses ×2 & remote level indicator', 'Chemical dosing system (oxygen scavenger, pH control)', 'Boiler feed pump (electric; steam-driven standby)', 'Bottom blowdown & continuous blowdown valves'],
    watchkeeping: ['Steam pressure — working 7 bar; SV lifts at 8.5 bar', 'Drum water level — maintain mid-glass; LOW LEVEL = critical emergency', 'Feed water pH 10.5–11.5; hardness below 5 ppm', 'Burner flame condition when oil-firing', 'Safety valve disc — check for weeping or wire drawing', 'Boiler water conductivity — purge if high', 'Blowdown schedule per chemical log']
  },
  {
    id: 'purifier', name: 'Fuel Oil Purifier', short: 'Alfa Laval FOPX 617 — ALCAP', rawCat: 'Fuel Treatment', icon: '🔄', color: '#5f9e1a', status: 'running',
    shortDesc: 'Self-cleaning centrifugal disc-stack separator removing water, sludge and catfines from HFO.',
    purpose: 'Removes water, sludge, catalytic fines (aluminium and silicon particles from refinery cracking), and solid contaminants from heavy fuel oil before it enters the service tanks — protecting injection equipment and the main engine.',
    role: 'Runs continuously 24/7 at sea. Two purifiers are typically fitted — one for HFO, one for diesel oil. The ALCAP system automatically monitors the water-oil interface and adjusts desludge timing for maximum separation.',
    importance: 'Catalytic fines (Mohs hardness 7) cause rapid wear of cylinder liners, piston rings, and fuel injection components. Water in fuel causes injection pump seizure and corrosion. Effective purification is the most critical factor protecting the main engine fuel system.',
    technical: 'Fuel enters the spinning bowl through a central distributor. The disc stack — hundreds of thin conical stainless steel discs — creates thousands of thin separation channels. Centrifugal force (6,000–8,000 G) separates water and sludge outward; clean fuel migrates inward to the paring disc outlet.',
    components: ['Rotating bowl assembly with self-cleaning mechanism', 'Conical disc stack (stainless steel)', 'Central distributor', 'Paring disc (clean oil outlet)', 'Gravity disc (controls water/oil interface)', 'Operating water system (hydraulic bowl open/close)', 'Drive motor, worm gear & bowl spindle', 'Feed heater (thermostatically controlled — 98 °C for HFO)', 'ALCAP water transducer & control unit'],
    watchkeeping: ['Bowl speed — nominal RPM; any drop = investigate immediately', 'Feed temperature — 98 °C for HFO', 'Vibration level — Class A normal; Class C = stop immediately', 'Sludge volume per desludge — log for trend monitoring', 'Motor current — no sustained overload', 'Clean oil outlet sight glass — should be clear', 'ALCAP water transducer alarm status']
  },
  {
    id: 'compressor', name: 'Starting Air Compressor', short: '2-Stage Reciprocating — 30 bar', rawCat: 'Propulsion', icon: '💨', color: '#7c3aed', status: 'standby',
    shortDesc: 'Two-stage water-cooled reciprocating compressor charging starting air receivers to 30 bar.',
    purpose: 'Compresses atmospheric air to 30 bar and stores it in starting air receivers for starting the main engine (by admitting high-pressure air to cylinders in firing order) and auxiliary engines, and for supplying pneumatic control valves throughout the vessel.',
    role: 'Operates automatically on pressure demand — starts when receiver pressure falls to ~24 bar, stops at ~30 bar. Two compressors are installed for full redundancy. Starting air is especially critical during manoeuvring.',
    importance: 'SOLAS Chapter II-1 requires sufficient compressed air for a minimum of 12 consecutive main engine starts in alternating directions. If starting air is lost, the main engine cannot be started — immobilising the vessel near restricted waters.',
    technical: 'A two-stage, water-cooled reciprocating compressor. Stage 1 (LP cylinder) compresses air to ~4–5 bar; an intercooler removes heat of compression; Stage 2 (HP cylinder) compresses to 30 bar. An aftercooler and moisture separator remove condensate before air enters the receivers.',
    components: ['LP cylinder — stage 1 (larger bore)', 'HP cylinder — stage 2 (smaller bore)', 'Intercooler with moisture separator', 'Aftercooler with moisture separator', 'Auto-drain valves on separators', 'Safety valves — LP set ~6 bar; HP set ~32 bar', 'Starting air receivers ×2 (2–6 m³ each at 30 bar)', 'Pressure switches for load/unload/auto-start'],
    watchkeeping: ['Receiver pressure — maintain 25–30 bar; never allow below 25 bar before manoeuvring', 'Inter-stage pressure — 4–5 bar; significant change indicates intercooler or valve fault', 'Discharge temperature — max 180 °C after aftercooler', 'Auto-drain valve — verify condensate discharge', 'Safety valve condition — check for weeping or lift marks', 'Motor current — no sustained overload above FLA']
  },
  {
    id: 'fwg', name: 'Fresh Water Generator', short: 'Vacuum Evaporator — 25 t/day', rawCat: 'Utilities', icon: '💧', color: '#0891b2', status: 'running',
    shortDesc: 'Low-temperature vacuum evaporator producing fresh water from seawater using main engine jacket water waste heat.',
    purpose: 'Produces fresh water from seawater for crew drinking and domestic use, main engine cooling system top-up, boiler feed water, and general ship service — reducing or eliminating the need to purchase bunker water in port.',
    role: 'Operates at sea when main engine jacket cooling water (JCW) is at sufficient temperature — minimum 70 °C, optimum 82–85 °C. The salinity cell continuously monitors product water, automatically diverting output if salinity exceeds 10 ppm.',
    importance: 'Fresh water is critical for crew health (WHO limit 200 ppm TDS; ship target below 10 ppm salinity), engine cooling system integrity, and boiler chemistry. On trans-oceanic passages of 20+ days, on-board production is essential.',
    technical: 'Reducing pressure lowers the boiling point of water. A brine ejector maintains ~0.93 bar vacuum in the evaporator shell, lowering the seawater boiling point to about 40 °C. Main engine JCW (80–88 °C) circulates through titanium plate heat exchangers, supplying the latent heat of evaporation.',
    components: ['Evaporator/heater section (titanium plate heat exchanger)', 'Condenser section (plate heat exchanger — seawater cooled)', 'Brine separator / demister pad', 'Brine ejector (seawater-driven — maintains vacuum)', 'Distillate pump (product water to FW tank)', 'Salinity cell, controller & automatic divert valve', 'JCW inlet/outlet isolation valves', 'Remineralisation dosing unit'],
    watchkeeping: ['Vacuum — maintain 0.88–0.94 bar; loss of vacuum = loss of production', 'JCW temperature to heater — minimum 70 °C (optimum 82–85 °C)', 'Production rate — record daily in Engine Room Log', 'Salinity of product water — maximum 10 ppm; auto-divert if exceeded', 'Heater plate differential pressure — rising DP indicates scaling', 'Ejector seawater supply pressure — adequate to maintain vacuum']
  },
  {
    id: 'sw-pump', name: 'Sea Water Cooling Pump', short: 'Centrifugal — 600 m³/h LT Circuit', rawCat: 'Cooling System', icon: '🌊', color: '#0369a1', status: 'running',
    shortDesc: 'Centrifugal pump circulating seawater through the central cooler for the LT fresh water cooling circuit.',
    purpose: 'Circulates seawater from the sea chest through the central cooler to remove heat from the low-temperature fresh water circuit, which cools the main engine charge air, lube oil, generators, compressors, and all other heat-generating machinery.',
    role: 'Runs continuously at sea. A standby pump is permanently on auto-start. Seawater is drawn from the sea chest through duplex auto-backflushing strainers, pumped through the central cooler, and discharged overboard.',
    importance: 'Loss of the seawater cooling pump removes cooling from the entire LT circuit, causing the main engine and all generators to reach high-temperature shutdown alarms within minutes. The standby pump must always be verified available and on auto-start.',
    technical: 'A horizontal, end-suction, single-stage centrifugal pump with a nickel-aluminium-bronze (NiAlBronze) impeller for seawater corrosion resistance. A mechanical shaft seal prevents seawater ingress along the pump shaft.',
    components: ['Volute pump casing (cast iron / epoxy coated)', 'NiAlBronze impeller with replaceable wearing rings', 'Mechanical shaft seal', 'Bearing housing with inboard and outboard bearings', 'Motor (440 V, 3-phase, IP55)', 'Duplex auto-backflushing sea chest strainer', 'Sea chest kingston valve (remote operated)', 'Overboard discharge valve & LT thermostatic bypass valve'],
    watchkeeping: ['Discharge pressure — compare to vessel reference; drop indicates wear or blockage', 'Strainer differential pressure — clean before alarm (switch to standby basket first)', 'Motor current — sustained overload above FLA = bearing or impeller fault', 'Bearing temperatures — maximum 80 °C', 'Mechanical seal drip rate — 10–30 drops per minute is normal; total loss = stop pump', 'Standby pump status — confirm on auto-start, correct rotation, valves open']
  },
  {
    id: 'steering-gear', name: 'Steering Gear', short: '4-Ram Hydraulic — Rapson Slide', rawCat: 'Steering & Control', icon: '🎯', color: '#9333ea', status: 'running',
    shortDesc: '4-ram hydraulic steering gear converting bridge helm orders into rudder movement — full SOLAS redundancy.',
    purpose: 'Converts helm orders from the bridge into physical angular movement of the rudder, providing directional control to navigate the vessel on the ordered course through hydrodynamic forces on the rudder blade.',
    role: 'Always operational at sea. SOLAS requires a pre-departure test within 12 hours of sailing. Port and starboard hydraulic systems are completely independent; either alone can move the rudder. Emergency steering at the steering gear room enables local control if bridge signals are lost.',
    importance: 'Loss of steering is a Category 1 SOLAS emergency. An uncontrolled vessel near restricted waters presents immediate risk of collision and grounding. SOLAS mandates the rudder must move from 35° to 30° in no more than 28 seconds.',
    technical: 'Two pairs of hydraulic rams act on a tiller arm on the rudder stock. A variable-displacement axial piston pump directs pressurised oil to extend one pair while the other retracts. The Rapson slide geometry provides mechanical advantage near hard-over positions.',
    components: ['Variable-displacement hydraulic pump units ×2', '4 actuating cylinders (double-acting hydraulic rams)', 'Tiller arm (forged, keyed to rudder stock)', 'Rudder stock — forged alloy steel', 'Electro-hydraulic servo / follow-up control unit', 'System and cylinder relief valves', 'Replenishing/header tank (hydraulic oil)', 'Emergency hand pump (SOLAS requirement)'],
    watchkeeping: ['Hydraulic oil level in replenishing tank — record daily; investigate any drop', 'Oil temperature — maximum 60 °C; high temp indicates relief valve bypassing', 'Hard-over test timing — must complete within 28 seconds (SOLAS)', 'Hunting or oscillation in follow-up mode — indicates feedback or valve fault', 'Oil cleanliness — sample quarterly; ISO 4406 Class 16/14/11', 'Emergency steering drill — monthly per SMS requirements']
  },
  {
    id: 'lo-purifier', name: 'Lube Oil Purifier', short: 'Alfa Laval LOPX — System Oil Centrifuge', rawCat: 'Lubrication', icon: '🟡', color: '#ca8a04', status: 'running',
    shortDesc: 'Centrifugal separator continuously cleaning main engine sump lube oil of water, sludge and combustion products.',
    purpose: 'Continuously removes water, combustion by-products, soot particles, metallic wear debris, and oxidation products from the main engine system lube oil (SAE 30) while the engine is running, maintaining oil cleanliness and extending service intervals.',
    role: 'Runs continuously at sea from the main engine sump, purifying the full sump volume approximately once every 2–3 hours. Works in parallel with the main engine full-flow lube oil filters. It is the primary defence against water contamination in the sump.',
    importance: 'Contaminated lube oil is the direct cause of a large proportion of main bearing, crankpin, and crosshead bearing failures. Water reduces oil film load-carrying capacity dramatically. Effective purification is essential to achieving designed overhaul intervals.',
    technical: 'Functionally identical to the fuel oil purifier but optimised for lubricating oil. The oil is heated to 90–95 °C to reduce viscosity. Many installations run as a clarifier (no water outlet) if water contamination is not anticipated, allowing higher throughput.',
    components: ['Rotating bowl with disc stack (optimised for LO viscosity)', 'Feed heater (thermostatically controlled — 90–95 °C)', 'Paring disc (clean oil outlet)', 'Operating water system', 'Drive motor, worm gear & bowl spindle', 'Temperature controller & safety thermostat', 'LO feed pump (gear type)', 'Control unit with alarm outputs'],
    watchkeeping: ['Bowl speed — nominal RPM; investigate any drop', 'Feed temperature — 90–95 °C for system lube oil', 'Vibration level — Class C = stop and inspect', 'Sludge volume per desludge — log for trend increase', 'Motor current — no sustained overload', 'TBN and viscosity of oil sample — review against engine maker minimum limits']
  },
  {
    id: 'oily-water', name: 'Oily Water Separator', short: '15 ppm Bilge Separator — MARPOL Annex I', rawCat: 'Environmental', icon: '🌍', color: '#059669', status: 'standby',
    shortDesc: 'Processes engine room bilge water to below 15 ppm oil content for MARPOL-compliant overboard discharge.',
    purpose: 'Separates oil from engine room bilge water to reduce oil content to below 15 ppm, enabling legal discharge of treated bilge water overboard in compliance with MARPOL Annex I Regulation 15.',
    role: 'Operated by the watchkeeping engineer on demand when the bilge well requires pumping. Cannot be used within special areas (Baltic, North Sea, Antarctic) or within 12 nautical miles of any coast. All operations must be recorded in the Oil Record Book Part I.',
    importance: 'Illegal discharge of oily bilge water is one of the most prosecuted maritime environmental offences globally. Under MARPOL Annex I, violations result in criminal prosecution of officers, heavy fines, and port state control blacklisting.',
    technical: 'A two-stage gravity and coalescing separation system. Stage 1 is a gravity separation tank. Stage 2 is a coalescing filter where fine oil droplets merge into larger droplets and rise to a collection chamber. The Oil Content Monitor (OCM) samples discharge using infrared absorption and closes the overboard valve if 15 ppm is exceeded.',
    components: ['Stage 1 gravity separation chamber', 'Stage 2 coalescing filter cartridges (replaceable)', 'Bilge feed pump (self-priming)', 'Oil Content Monitor (OCM — MEPC certified)', 'Automatic overboard stop valve (solenoid-actuated)', 'Oil collection chamber & drain valve', 'Oil Record Book (ORB) interface'],
    watchkeeping: ['OCM reading — must remain below 15 ppm for overboard discharge', 'Vessel position — confirm outside 12 nm from land; not in special area', 'Filter cartridge differential pressure — replace when alarm activates', 'OCM calibration certificate — valid and endorsed by class surveyor', 'Oil Record Book — complete entries accurately before, during and after every operation', 'Chemical contamination check — do NOT process chemically contaminated bilge through OWS']
  },
  {
    id: 'incinerator', name: 'Incinerator', short: 'Teamtec OG 400 — Shipboard Waste Incinerator', rawCat: 'Environmental', icon: '🔥', color: '#ea7018', status: 'standby',
    shortDesc: 'MARPOL Annex VI-compliant incinerator for burning sludge, garbage and solid waste at sea.',
    purpose: 'Disposes of shipboard waste including fuel oil sludge, lube oil sludge, oily rags, food waste, and garbage by high-temperature combustion, reducing waste volume and enabling legal disposal at sea under MARPOL Annex VI Regulation 16.',
    role: 'Operated at sea only — minimum 12 nautical miles from land. Cannot be used in port or in special areas. Operated by the watchkeeping engineer or motorman. Purifier room sludge is pumped to the sludge tank for batch burning.',
    importance: 'Sludge tank capacity is finite; once full, the purifier cannot operate and fuel treatment fails. MARPOL Annex VI requires minimum combustion temperatures — 850 °C for normal waste — to prevent unburnt hydrocarbon and dioxin emissions.',
    technical: 'A refractory-lined cylindrical combustion chamber with primary and secondary afterburner. The primary burner ignites the charge; the secondary ensures complete combustion at temperatures exceeding 850 °C. An induced draught fan maintains slight negative pressure in the chamber.',
    components: ['Primary refractory-lined combustion chamber', 'Primary fuel oil burner (HFO or MDO)', 'Secondary afterburner (maintains 850 °C minimum)', 'Sludge pump & sludge feed system', 'Solid waste loading door with safety interlock', 'Induced draught fan', 'Flue gas stack with spark arrestor', 'Ash tray & ash collection system'],
    watchkeeping: ['Combustion chamber temperature — minimum 650 °C solid waste; 850 °C for sludge', 'Primary and secondary burner flame — stable, no sooting or black smoke', 'Draught pressure — maintain slight negative; positive = unsafe, stop', 'Sludge feed rate — match to burner capacity to avoid flooding', 'Vessel position — confirm outside 12 nm before starting', 'Prohibited materials check — no PCBs, halogenated plastics, or sewage']
  },
  {
    id: 'sewage', name: 'Sewage Treatment Plant', short: 'Biological / Electrochemical STP', rawCat: 'Environmental', icon: '🌿', color: '#2a9e6e', status: 'running',
    shortDesc: 'Biological sewage treatment plant processing black and grey water for MARPOL Annex IV-compliant discharge.',
    purpose: 'Treats shipboard sewage — black water from toilets and grey water from washrooms and galleys — to a standard meeting MARPOL Annex IV requirements, enabling legal overboard discharge at sea.',
    role: 'Operates continuously at sea once activated. Discharge overboard is permitted outside 3 nautical miles from land for certified treated effluent. Within 3 nm and in port, all sewage must be retained in the holding tank.',
    importance: 'Discharge of untreated sewage pollutes coastal waters and poses public health risks. MARPOL Annex IV applies to vessels over 400 GT. Non-compliance results in port state detention and significant fines, particularly in the Baltic Sea special area.',
    technical: 'Aerobic bacteria in the aeration/reaction tank biologically oxidise organic matter. Air is continuously supplied to support bacterial metabolism. Treated effluent passes to a settling tank, then is disinfected by chlorination or UV irradiation.',
    components: ['Aeration/reaction tank (biological oxidation)', 'Air blower/compressor', 'Settling/clarification chamber', 'Disinfection unit — chlorinator or UV lamp', 'Sludge return pump', 'Effluent discharge pump', 'Holding tank (port and restricted waters)', 'Comminuter/macerator'],
    watchkeeping: ['Aeration air supply — blower running; adequate pressure and flow', 'Biological activity — healthy foaming in aeration tank', 'UV lamp intensity — check hours against replacement interval', 'Overboard discharge valve — confirm closed in port and within 3 nm', 'Chlorine residual in treated effluent — verify per manufacturer specification']
  },
  {
    id: 'emergency-gen', name: 'Emergency Generator', short: 'Caterpillar C18 — 500 kW / 440 V', rawCat: 'Power Generation', icon: '⚡', color: '#ca9b0a', status: 'standby',
    shortDesc: 'SOLAS-mandated emergency diesel generator auto-starting within 45 seconds of blackout.',
    purpose: 'Provides emergency electrical power to all SOLAS-required services on total main power loss: emergency lighting, navigation lights, fire detection, fire pumps, lifeboat davit winches, GMDSS radio, EPIRB charging, and emergency steering.',
    role: 'On continuous auto-start standby at all times. Must start automatically and achieve full rated voltage within 45 seconds of main power failure. Located above the main deck in a separate space, independent of the engine room.',
    importance: 'The emergency generator is the absolute last line of defence against total loss of power. Without it, a blacked-out vessel in congested waters has no navigation lights, no communications, no fire detection, and no steering.',
    technical: 'A compact 4-stroke diesel engine driving an alternator at 440 V / 60 Hz. The starting system is battery-operated — completely independent of main machinery compressed air. An automatic transfer switch (ATS) detects loss of main busbar voltage and commands the engine to start.',
    components: ['4-stroke diesel engine (compact, turbocharged)', 'Battery starting system (independent of starting air)', 'Battery charger', 'Alternator (440 V, 60 Hz; 18-hour continuous rating)', 'Automatic Transfer Switch (ATS)', 'Emergency switchboard (SOLAS-defined loads only)', 'Engine pre-heater', 'Fuel day tank (gravity feed — 18 hours at full load)'],
    watchkeeping: ['Battery condition — verify state of charge; critical for auto-start', 'Engine pre-heater — jacket water at starting temperature', 'Fuel day tank level — minimum 18 hours capacity at full load', 'Auto-start test — conduct weekly; record start time (must be under 45 seconds)', 'Ventilation — confirm flaps open; manual flap must always be open', 'Annual test — full blackout simulation with class surveyor']
  },
  {
    id: 'air-cooler', name: 'Scavenge Air Cooler', short: 'Main Engine Charge Air Cooler', rawCat: 'Propulsion', icon: '❄️', color: '#0ea5e9', status: 'running',
    shortDesc: 'Cools turbocharger compressed charge air from ~200 °C to 35–50 °C to increase air density and engine power.',
    purpose: 'Cools the compressed charge air delivered by the turbocharger from approximately 180–220 °C down to 35–50 °C before it enters the cylinders, dramatically increasing air density and thus the oxygen mass available per cylinder stroke.',
    role: 'Integral part of the main engine, mounted between the turbocharger compressor outlet and the scavenge air receiver. Cooling water is supplied from the LT fresh water circuit. Condensate drains must be regularly checked — water carry-over into cylinders causes hydraulic lock.',
    importance: 'Without effective charge air cooling, hot low-density air reduces power output, increases thermal loading on pistons and liners, and raises NOx formation. Even a 5 °C rise in charge air temperature produces a measurable power loss.',
    technical: 'A shell-and-tube heat exchanger. The air side (shell) receives scavenge air from the turbocharger; the tube side carries LT cooling water. High-efficiency fins on the tubes increase heat transfer area.',
    components: ['Tube bundle (cupro-nickel or titanium tubes)', 'Finned tubes (extended surface for heat transfer)', 'Shell casing (integral with engine structure)', 'LT cooling water inlet and outlet connections', 'Condensate drain tray and drain valve (MUST be open at start)', 'Air inlet from turbocharger and outlet to scavenge receiver', 'Sacrificial zinc anodes (water-side corrosion protection)'],
    watchkeeping: ['Air outlet temperature after cooler — target 35–50 °C depending on sea temperature', 'Differential pressure across air side — increasing DP indicates air-side fouling', 'Condensate drain — check for water accumulation; investigate if excessive', 'Zinc anode condition — replace when 50% wasted', 'Oil in condensate drain — indicates piston ring blow-by or turbocharger seal problem', 'No air-side water leak after maintenance — verify by hydraulic test before starting']
  },
  {
    id: 'fuel-system', name: 'Fuel Oil System', short: 'HFO/MDO Conditioning & Injection', rawCat: 'Fuel System', icon: '🛢', color: '#c2520a', status: 'running',
    shortDesc: 'Conditions HFO from service tank to precise injection viscosity of 13–17 cSt for main engine cylinders.',
    purpose: 'Conditions heavy fuel oil from the service tank to the precise temperature, pressure, and viscosity required for injection — delivering fuel at the correct viscosity of 13–17 cSt and injection pressures of 600–1,000 bar at the individual cylinder fuel injectors.',
    role: 'Operates continuously whenever the main engine is running. Comprises the LP booster circuit (draws fuel, heats it, conditions viscosity) and the HP injection circuit on each cylinder driven by camshaft-operated or common-rail fuel injection pumps.',
    importance: 'Too high a viscosity results in poor atomisation, incomplete combustion, carbon deposits, and injection pump wear. Too low a viscosity causes pump leakage and fire risk. The fuel system is also where MARPOL ECA changeover procedures are executed.',
    technical: 'LP circuit: fuel is drawn by booster pumps through duplex auto-backflushing filters (50 micron) and a steam-heated fuel oil heater. A viscosity controller measures kinematic viscosity and adjusts heater steam to maintain constant injection viscosity.',
    components: ['Fuel oil service tanks — HFO and MDO/MGO', 'Fuel oil booster pumps ×2 (LP circuit, duty/standby)', 'Duplex auto-backflushing fuel oil filters (50 micron)', 'Fuel oil heater (steam-heated shell and tube)', 'Viscosity controller (capillary or rotational type)', 'Fuel oil pressure regulating valve', 'Individual HP fuel injection pumps per cylinder', 'Fuel injector with needle valve and multi-hole atomiser tip'],
    watchkeeping: ['Fuel oil viscosity at engine inlet — 13–17 cSt; critical for injection quality', 'Fuel oil temperature — 130–145 °C for HFO', 'Filter differential pressure — clean/switch before alarm; note trend', 'ECA entry changeover procedure — follow vessel SMS with temperature log', 'Service tank contents — monitor consumption; log daily per fuel type', 'Injector performance — monitor exhaust gas temperatures per cylinder']
  },
  {
    id: 'lo-system', name: 'Lube Oil System', short: 'Forced Circulation — SAE 30 / 25,000 L Sump', rawCat: 'Lubrication', icon: '🔶', color: '#d97706', status: 'running',
    shortDesc: 'Forced-circulation lube oil system delivering SAE 30 system oil at 4.5 bar to all main engine bearings.',
    purpose: 'Circulates pressurised lube oil to all main engine bearing surfaces — main bearings, crankpin bearings, crosshead bearings, camshaft bearings, and turbocharger bearings — forming a hydrodynamic film that prevents metal-to-metal contact and removes frictional heat.',
    role: 'Operates whenever the main engine is running. Pre-lube pump starts 3 minutes before engine start, establishing oil pressure to all bearings. Post-lube pump continues circulation for 15 minutes after engine stop, cooling bearings and preventing heat soak damage.',
    importance: 'Inadequate lubrication pressure or contaminated lube oil is the leading cause of bearing failures aboard. A main bearing seizure at sea requires drydock — a multi-million dollar repair. The TBN of the oil must be maintained above the engine maker minimum to neutralise sulphuric acid from burning HFO.',
    technical: 'A gear-type main pump is crankshaft gear driven — engine speed directly determines oil flow. The lube oil cooler reduces bulk oil temperature. A thermostatic bypass valve controls oil inlet temperature. Full-flow auto-backflush filters remove particles above 25–40 micron.',
    components: ['Main-driven gear oil pump (crankshaft gear train driven)', 'Pre-lubrication pump (electric — independent)', 'Post-lubrication pump (electric — independent)', 'Lube oil cooler (shell and tube — HT freshwater side)', 'Thermostatic temperature control valve', 'Full-flow auto-backflush lube oil filter', 'Main engine sump under bedplate (20,000–30,000 litres)'],
    watchkeeping: ['LO inlet pressure to engine — minimum 2.8 bar; LOW PRESSURE = immediate shutdown', 'LO inlet temperature — 43–48 °C', 'LO cooler performance — outlet temperature vs HT water inlet temperature', 'Filter differential pressure — clean/switch before alarm setpoint', 'Sump level — check daily; top up with approved oil; do NOT mix oil grades', 'TBN of oil sample — must remain above engine maker minimum vs fuel sulphur']
  },
  {
    id: 'cooling-system', name: 'Jacket Water Cooling', short: 'HT & LT Freshwater Cooling Circuits', rawCat: 'Cooling System', icon: '❄', color: '#3b82f6', status: 'running',
    shortDesc: 'HT circuit cools the main engine jacket; LT circuit cools charge air, lube oil, generators and auxiliaries.',
    purpose: 'Removes heat from the main engine cylinders, piston crowns, cylinder heads, and exhaust valves (HT circuit), and on the low-temperature circuit cools charge air coolers, lube oil coolers, generator cooling, and the fresh water generator.',
    role: 'Two-circuit closed fresh water system: HT circuit (70–85 °C) serves the main engine jacket and heads; LT circuit (25–38 °C) serves charge air coolers, lube oil coolers, and auxiliaries. The LT circuit is cooled by the seawater central cooler.',
    importance: 'Cylinder jacket temperature must stay within a precise band. Below 60 °C, sulphuric acid condensation from HFO combustion corrodes liner surfaces ("cold corrosion"). Above 90 °C, boiling at hot spots causes cavitation damage.',
    technical: 'HT circuit: jacket water pump circulates water through cylinder jackets, heads, and exhaust valve cages. Temperature control is via thermostatic three-way valve. LT circuit: seawater-cooled via the central cooler. Both circuits have expansion tanks, chemical dosing, and pre-heaters.',
    components: ['HT jacket water pump — main-driven and electric standby', 'HT jacket water pre-heater', 'HT thermostatic bypass valve', 'LT jacket water pump — electric driven duty/standby', 'Central cooler (plate heat exchanger — LT to seawater)', 'LT thermostatic temperature control valve', 'Expansion / header tanks for HT and LT circuits', 'Chemical dosing system (corrosion inhibitor)'],
    watchkeeping: ['HT water outlet temperature from engine — 78–88 °C; investigate any rapid change', 'LT water temperature to charge air cooler — 28–35 °C', 'Expansion tank levels — check daily; any drop indicates system leakage', 'Water chemistry — test inhibitor concentration weekly; pH 7–9', 'High-temperature alarms — test monthly']
  },
  {
    id: 'ballast-pump', name: 'Ballast Pump', short: 'Centrifugal Ballast Pump — 800 m³/h', rawCat: 'Hull & Piping', icon: '⚓', color: '#2563eb', status: 'standby',
    shortDesc: 'Large centrifugal pump filling and emptying ballast tanks to maintain vessel stability, trim and draft.',
    purpose: 'Fills and empties the ballast tanks distributed around the vessel hull to maintain safe stability (GM and GZ curve), longitudinal trim, and acceptable draft for weather, cargo loading, and port entry conditions.',
    role: 'Used during cargo operations in port to compensate for changing cargo weight and maintain the vessel upright. Also used at sea when weather conditions require adjusting trim or stability. Operated from the cargo control room under the direction of the officer responsible for stability management.',
    importance: 'Inadequate ballast management is a leading cause of vessel loss and structural damage. An improperly ballasted vessel may have insufficient stability (risk of capsize) or excessive hull bending stress. SOLAS Chapter II-1 requires all vessels to maintain positive stability at all loading conditions.',
    technical: 'A centrifugal pump (typically 800–1,500 m³/h) with a large bore, low-head impeller optimised for high flow at moderate pressure. BWTS (Ballast Water Treatment System) is mandatory under the IMO BWM Convention to prevent transfer of invasive aquatic species.',
    components: ['Large bore centrifugal pump (800–1,500 m³/h)', 'Electric motor (200–500 kW)', 'Sea chest connection and strainer', 'Ballast main and branch piping (300–600 mm)', 'Remote-operated hydraulic or electric tank valves', 'Ballast tank level transmitters and high-level alarms', 'Ballast Water Treatment System (BWTS — UV or electrochlorination)'],
    watchkeeping: ['Tank levels — monitor continuously during ballasting/deballasting', 'Stability calculations — update Loading Computer before and after each operation', 'BWTS — ensure operational when taking on ballast in a new port area', 'Overfill prevention — never leave an unattended ballasting operation', 'BWTS record book — log all ballast water exchanges per BWM Convention']
  },
  {
    id: 'sea-chest', name: 'Sea Chest & Kingstons', short: 'Hull Valves — Seawater Inlet & Overboard', rawCat: 'Hull & Piping', icon: '🔵', color: '#0891b2', status: 'running',
    shortDesc: 'Sea chest inlets and overboard discharge valves admitting seawater to and discharging from all shipboard systems.',
    purpose: 'Admit seawater from the sea to supply all shipboard seawater systems — main cooling, fire main, ballast, bilge, and deck wash — and provide overboard discharge paths for treated effluents and cooling water return in compliance with MARPOL regulations.',
    role: 'Sea chest kingstons are normally kept open at sea and closed only for maintenance or damage control. High and low sea chests provide redundancy. Overboard discharge valves must be confirmed closed before dry-docking.',
    importance: 'Sea chest blockage causes immediate loss of cooling to all seawater systems, potentially leading to main engine shutdown within minutes. The kingstons are the interface between the vessel\'s internal systems and the sea; any sea chest defect is a penetration of the hull below the waterline.',
    technical: 'Sea chests are box-shaped chambers built into the ship\'s hull plating, covered by a grating on the outer hull to exclude large debris. Inside the hull, a kingston valve isolates the sea chest from the internal piping.',
    components: ['Sea chest box or cylinder (built into hull plating)', 'External sea chest grating (removable for drydock inspection)', 'Kingston valve — gate type or butterfly type (hydraulic remote)', 'Internal sea chest strainer basket', 'High sea chest (above bilge keel — rough weather)', 'Low sea chest (below bilge keel — calm conditions)', 'Overboard discharge valves (non-return or gate type)'],
    watchkeeping: ['Sea chest strainer differential pressure — clean if pressure drop increases', 'Cooling water supply pressure — sudden drop may indicate sea chest blockage', 'Sea temperature — monitor in sub-zero conditions; risk of ice formation on gratings', 'Kingston valve position — confirm open; log any remote operation', 'MARPOL compliance — confirm each overboard discharge is from an authorised system']
  },
  {
    id: 'bilge-system', name: 'Bilge System', short: 'Bilge Pump & Main Ring Pipe', rawCat: 'Hull & Piping', icon: '💧', color: '#6366f1', status: 'standby',
    shortDesc: 'Pumping system removing water accumulation from watertight compartments throughout the vessel.',
    purpose: 'Removes water accumulations from the bilges of all watertight compartments — engine room, cargo holds, fore peak, aft peak, and void spaces — preventing buildup that would reduce freeboard, degrade stability, and cause corrosion.',
    role: 'Operated as required on each watch to pump out bilge wells when they accumulate water. Engine room bilge is processed through the OWS before overboard discharge. A functioning bilge system is one of the most fundamental safety requirements for any vessel.',
    importance: 'In a progressive flooding scenario, the bilge pumps are the first line of defence after damage control measures. SOLAS Chapter II-1 specifies minimum bilge pump capacity for each vessel type. A rising bilge may be the first indication of a hull breach.',
    technical: 'A ring main system consists of a bilge main pipe running the full length of the vessel with branch pipes to each compartment bilge well. Strum boxes (strainers) at each bilge well prevent debris blocking the pipework. Non-return valves prevent back-flooding between compartments.',
    components: ['Bilge main pipe (ring main — full vessel length)', 'Branch bilge pipes to each compartment', 'Strum boxes / strainer baskets at each bilge well', 'Bilge pumps — general service (centrifugal, self-priming)', 'Emergency bilge suction from ballast pump (engine room)', 'Non-return (check) valves on branch connections', 'Bilge well level sensors and high-level alarms'],
    watchkeeping: ['Engine room bilge level — check and pump as required each watch', 'Rising bilge level — investigate cause immediately; may indicate hull breach', 'OWS compliance — process engine room bilge through OWS before overboard', 'Strum box condition — clean if suction drops off during pumping', 'High bilge alarms — test monthly per IAS maintenance schedule', 'ORB entries — complete all bilge pumping operations in Oil Record Book']
  },
  {
    id: 'firemain', name: 'Fire Main & Fire Pumps', short: 'SOLAS Fire Main — 2 × Fire Pumps + Emergency', rawCat: 'Fire & Safety', icon: '🔴', color: '#dc2626', status: 'standby',
    shortDesc: 'SOLAS-required pressurised fire main with dedicated fire pumps serving all fire hydrants and sprinklers aboard.',
    purpose: 'Provides a pressurised supply of seawater to all fire hydrants, monitor nozzles, deck wash connections, and the sprinkler system throughout the vessel for firefighting and fire prevention.',
    role: 'Two main fire pumps (independently powered) are required by SOLAS; one must be operable with the main machinery space isolated. An emergency fire pump is located outside the engine room — activated from the bridge or locally if the engine room is abandoned.',
    importance: 'Fire is one of the three most serious hazards at sea. A loss of fire main pressure when a fire breaks out can result in inability to fight the fire, forcing evacuation and total vessel loss. SOLAS Chapter II-2 specifies minimum fire pump capacity and minimum pressure at all hydrants (0.25 MPa).',
    technical: 'Two centrifugal seawater pumps draw from the sea chest and discharge into the fire main ring pipe. The fire main is a looped system so any section can be isolated for maintenance. The emergency fire pump must be located outside the engine room.',
    components: ['Main fire pumps ×2 (centrifugal, seawater, 160–300 m³/h each)', 'Emergency fire pump (diesel or emergency power driven)', 'Fire main ring piping (looped — isolatable by section valves)', 'International shore connection', 'Fire hydrants at each deck station (15 m spacing)', 'Fire hose cabinets with hose and nozzle', 'Isolating valves (section valves for maintenance)'],
    watchkeeping: ['Fire pump availability — both main pumps ready; emergency pump operable', 'Weekly fire pump test — run each main pump minimum 30 minutes per SMS', 'Emergency fire pump starting — quarterly test from remote starting position', 'Fire main pressure after starting — minimum 0.25 MPa at highest hydrant', 'Fire hose cabinet — hose dry, nozzle clean and undamaged', 'Fire detection system — test per planned maintenance schedule']
  },
  {
    id: 'co2-system', name: 'CO2 Fixed Fire System', short: 'Total Flood CO2 — Engine Room & Cargo', rawCat: 'Fire & Safety', icon: '⚠️', color: '#6b7280', status: 'standby',
    shortDesc: 'Total flooding fixed CO2 fire suppression system for engine room, cargo pump room and cargo spaces.',
    purpose: 'Provides a fixed total-flood fire suppression capability for enclosed spaces — primarily the engine room and cargo pump room — where a conventional water fire main cannot effectively extinguish Class B (hydrocarbon) fires.',
    role: 'Activated only after the space has been evacuated and sealed (all ventilation stopped, all openings closed). Operated from outside the protected space via a two-step release system. Strictly a last resort after personnel evacuation is confirmed.',
    importance: 'Engine room fires involving fuel oil can escalate extremely rapidly. CO2 at flooding concentrations (34% by volume) causes rapid unconsciousness and death — systems must be safeguarded with two-action release and audible personnel alarms.',
    technical: 'CO2 is stored as a liquid under pressure in cylinders (typically 45 or 67.5 kg each) in the CO2 room, always outside the protected space. The total number of cylinders is calculated to achieve 30% flooding volume in the largest protected space within 2 minutes.',
    components: ['CO2 cylinders (45 or 67.5 kg each)', 'Cylinder bank manifold and discharge pipe', 'Two-stage release control cabinet (outside protected space)', 'Section valves per protected space', 'Distribution piping and overhead discharge nozzles', 'Low-pressure alarm (cylinder leakage detector)', 'Evacuation alarm (audible — in protected space)', 'Ventilation shutdown interlock'],
    watchkeeping: ['CO2 cylinder weight — verify all cylinders full per annual inspection record', 'Two-stage release mechanism — familiarise all engineers', 'Distribution piping — inspect annually for corrosion and blockage', 'Ventilation trip interlock — test annually', 'CO2 room door — kept closed; room must be ventilated before entry after any leak', 'Annual service by certified CO2 service technician — mandatory per class requirements']
  },
  {
    id: 'ias', name: 'Integrated Automation System', short: 'IAS — Kongsberg K-Chief or Equivalent', rawCat: 'Automation & Control', icon: '💻', color: '#7c3aed', status: 'running',
    shortDesc: 'Vessel-wide automation platform monitoring, alarming and controlling machinery systems from the ECR.',
    purpose: 'The IAS monitors all machinery parameters, generates alarms for out-of-range conditions, controls automated functions (pump start/stop, valve operation), manages alarm acknowledgement and logs, and provides the watchkeeping engineer with a complete operational picture from the ECR.',
    role: 'Continuously active 24/7 at sea and in port. All machinery sensors feed signals to IAS remote I/O cabinets networked back to the ECR operator stations. The IAS takes over automated control functions — starting standby pumps, opening/closing valves, initiating safety shutdowns — supporting UMS (Unmanned Machinery Space) operation.',
    importance: 'Modern vessels are classed for UMS operation, allowing the engine room to be left unattended with only an officer on call. The IAS is the technological foundation of UMS. The IAS alarm log is also essential for fault diagnosis, insurance claims, and port state control inspections.',
    technical: 'The IAS consists of operator workstations (SCADA-style graphical displays showing P&ID mimics), remote I/O cabinets (collecting sensor signals), a dual-redundant process controller, an alarm server and printer, and network infrastructure. Safety functions are hardwired independently of the IAS main processing network.',
    components: ['ECR operator workstations (typically 2–3 screens)', 'Remote I/O cabinets in engine room and all machinery spaces', 'Dual-redundant process controllers (hot standby)', 'Alarm server and alarm printer', 'Field sensors — pressure, temperature, level, flow, vibration transmitters', 'Solenoid valves, motor starters and frequency drives under IAS control', 'UMS alarm extension to bridge and officers\' cabins', 'UPS backed power supply'],
    watchkeeping: ['Alarm list status — review at start of each watch; no standing unacknowledged alarms', 'Analogue point health — check for sensor failures (frozen readings)', 'Standby pump auto-start test — verify function periodically', 'IAS backup power — UPS condition and battery test', 'Alarm printer — paper loaded; print test at each watch takeover', 'ECR watchkeeping log — record any IAS alarms and corrective actions taken']
  },
  {
    id: 'turbocharger', name: 'Turbocharger', short: 'ABB TPL / MET Series — Exhaust Gas Turbocharger', rawCat: 'Propulsion', icon: '🌀', color: '#e879f9', status: 'running',
    shortDesc: 'Exhaust gas-driven turbocharger compressing scavenge air to increase main engine power and efficiency.',
    purpose: 'Recovers energy from the main engine exhaust gases and uses it to compress the incoming scavenge air, increasing air density and thus the oxygen mass entering the cylinders per stroke — enabling higher fuel injection quantity and greater power output.',
    role: 'Operates automatically whenever the main engine is running — the exhaust gas turbine side is driven by ME exhaust gases; the compressor side compresses atmospheric air. On modern large-bore slow-speed engines, one or two turbochargers serve all cylinders.',
    importance: 'The turbocharger is responsible for the thermal efficiency advantage of the modern marine diesel engine. Without turbocharging, a 2-stroke engine could not achieve specific fuel consumption below 200 g/kWh; modern turbocharged engines achieve 155–165 g/kWh. A failed turbocharger reduces engine power to approximately 30–40% of normal output.',
    technical: 'The turbine wheel (nickel superalloy) and compressor wheel (aluminium alloy) are mounted on a common shaft supported by sleeve bearings lubricated by the main engine lube oil system. Hot exhaust gas (400–500 °C) expands through the turbine nozzle ring at 8,000–15,000 RPM, compressing air to a pressure ratio of 3.5–5.0:1.',
    components: ['Turbine wheel (nickel superalloy — high temperature)', 'Compressor wheel (aluminium alloy)', 'Rotor shaft', 'Sleeve bearings (lube oil from ME system)', 'Turbine nozzle ring (fixed guide vanes)', 'Compressor casing and air inlet filter/silencer', 'Water washing connection (turbine side)'],
    watchkeeping: ['Turbocharger RPM — compare to expected value at current engine load; drop indicates fouling', 'Lube oil pressure to turbocharger — minimum per maker spec; loss of LO = emergency stop TC', 'Vibration level — increased vibration indicates bearing wear or rotor imbalance', 'Air filter differential pressure — clean or replace when fouled', 'Turbine washing schedule — follow maker interval; log each wash', 'Annual inspection — open casing inspection; measure bearing clearances']
  },
  {
    id: 'domestic', name: 'Freshwater & Domestic System', short: 'Domestic Water Calorifier & Pressure Tank', rawCat: 'Utilities', icon: '🚿', color: '#0891b2', status: 'running',
    shortDesc: 'Pressurised domestic fresh water system supplying potable hot and cold water to all accommodation spaces.',
    purpose: 'Provides crew with pressurised potable cold water and hot water for drinking, cooking, washing, sanitary facilities, and all domestic uses throughout the accommodation block, engine room, and working spaces.',
    role: 'Operates continuously. Potable water from the FW tank is drawn through a UV sterilisation unit and pressure booster pump, pressurised to 3–4 bar by a pressure tank (hydrophore), and distributed throughout the vessel. A calorifier provides hot water at 60 °C to prevent Legionella growth.',
    importance: 'Potable water quality is a public health requirement. Legionella pneumophila thrives in water between 20–45 °C — inadequate hot water temperature can cause Legionnaires\' disease among crew. The ILO Maritime Labour Convention (MLC 2006) mandates adequate supply of safe potable water for all crew.',
    technical: 'The pressure tank (hydrophore) contains a pre-charged air cushion that maintains system pressure without the pump running continuously. The calorifier is typically a 500–1,000 litre insulated tank heated to 65 °C. UV sterilisation at the tank outlet destroys bacteria.',
    components: ['Fresh water tank (holding — from FWG or bunker water)', 'UV sterilisation unit', 'Pressure booster pump (centrifugal, electric)', 'Hydrophore tank (pressure tank with air cushion)', 'Calorifier (insulated hot water tank — 500–1,000 L)', 'Electric immersion heater in calorifier', 'Jacket water or steam coil in calorifier', 'Chlorine dosing system'],
    watchkeeping: ['Hot water temperature — minimum 60 °C to prevent Legionella growth', 'Cold water temperature — should not exceed 20 °C', 'Pump starts per hour — excessive starts indicate pressure tank fault', 'UV sterilisation lamp — check hours against replacement interval', 'Chlorine residual — test at distribution outlets; minimum 0.2 ppm', 'FW tank level — log daily; ensure adequate supply for voyage']
  },
  {
    id: 'provision-ref', name: 'Provision Refrigeration', short: 'R134a / R404A Provision & Cargo Ref Plant', rawCat: 'Utilities', icon: '❄️', color: '#38bdf8', status: 'running',
    shortDesc: 'Vapour compression refrigeration system maintaining provision stores and cargo refrigeration at specified temperatures.',
    purpose: 'Maintains crew provision stores (vegetable room, meat room, fish room, dairy room) at safe food storage temperatures — typically +4 °C for chilled stores and -18 °C for frozen stores — and on reefer vessels, maintains the cargo holds at the consignee-specified temperature.',
    role: 'Operates continuously at sea and in port. Provision refrigeration is a crew welfare requirement under MLC 2006. Cargo refrigeration on container ships and reefer vessels is a commercial requirement — temperature excursions may render cargo unsaleable.',
    importance: 'Loss of provision refrigeration in tropical climates can render food unsafe within hours. Cargo temperature excursions on perishable goods cause total cargo loss worth millions of dollars per voyage. Cargo temperature is governed by Bill of Lading temperature clauses.',
    technical: 'A vapour compression refrigeration cycle: refrigerant (R134a or R404A) is compressed, condensed in the seawater-cooled condenser, expanded through a thermostatic expansion valve, and evaporated in the evaporator coils inside the refrigerated space — absorbing heat from the space contents.',
    components: ['Refrigeration compressor (reciprocating or screw type)', 'Seawater-cooled condenser (shell and tube or plate type)', 'Thermostatic expansion valve (TEV) per circuit', 'Evaporator coils in each refrigerated space', 'Receiver (liquid refrigerant storage)', 'Hot gas defrost system', 'Temperature controllers and thermostats per compartment', 'Sight glass (liquid line — refrigerant level and moisture indicator)'],
    watchkeeping: ['Space temperatures — check all provision rooms and cargo holds; log each watch', 'Suction and discharge pressures — compare to design for current operating temperatures', 'Sight glass — clear (not bubbling) confirms adequate refrigerant charge', 'Condenser cooling water — check flow; condenser pressure should not be excessive', 'Refrigerant leaks — check with leak detector monthly; log any loss (F-Gas log)', 'Compressor oil level — check crankcase sight glass; no milky appearance']
  },
  {
    id: 'lifeboat', name: 'Lifeboat & Rescue Boat', short: 'Enclosed Lifeboat & Davit — SOLAS III', rawCat: 'Fire & Safety', icon: '⛵', color: '#ca9b0a', status: 'standby',
    shortDesc: 'SOLAS-compliant enclosed lifeboats, davits and launching systems providing embarkation capacity for all persons.',
    purpose: 'Provides safe embarkation, launching, and propulsion for all persons aboard in an emergency requiring abandonment of the vessel, in compliance with SOLAS Chapter III — Life-Saving Appliances.',
    role: 'On continuous standby at all times. Weekly operational checks required by SOLAS. Monthly boat drills are mandatory under SOLAS regulation III/19. Boats must be ready to launch within 5 minutes. The rescue boat is deployed for man-overboard recovery.',
    importance: 'In extremis, the lifeboat is the last resort for crew survival. Failure of a lifeboat launching system at the time of abandonment can directly cost lives. SOLAS Chapter III sets the highest possible standards for LSA maintenance and crew training.',
    technical: 'An enclosed GRP lifeboat suspended from on-load release gravity davits. The davit consists of a structural arm, wire falls, and a winch. On-load release hooks open simultaneously at water level when operated from inside the boat, even under full load.',
    components: ['Enclosed GRP lifeboat (capacity for all persons aboard plus 10%)', 'Gravity davit arms (port and starboard)', 'Wire falls and winch (electric and manual operation)', 'On-load release hooks (SOLAS-compliant)', 'Boat diesel engine (cold-start within 2 pulls)', 'EPIRB and SART', 'Survival stores — per SOLAS III Schedule'],
    watchkeeping: ['Weekly visual inspection — boat condition, engine fluid levels, release mechanisms clear', 'Monthly boat drill — all crew participate', 'Monthly engine test — run lifeboat engine at idle for minimum 3 minutes', 'Falls wire inspection — examine for broken wires, corrosion, kinks', 'Provisions check — water, food, and pyrotechnics within expiry dates', '5-year on-load release hook service — mandatory by certified service technician']
  },
  {
    id: 'shaft-prop', name: 'Shaft & Propeller', short: 'Fixed Pitch Propeller — Tail Shaft & Stern Tube', rawCat: 'Propulsion', icon: '⚙️', color: '#0ea5e9', status: 'running',
    shortDesc: 'Propeller shaft line transmitting main engine torque to the fixed-pitch propeller for vessel propulsion.',
    purpose: 'Transmits the rotary torque generated by the main engine crankshaft through the intermediate shaft, shaft bearings, and stern tube to the fixed-pitch propeller, converting mechanical energy into hydrodynamic thrust to move the vessel.',
    role: 'The shafting system runs continuously at sea. The intermediate shaft passes through oil-lubricated plummer block bearings. The stern tube seals the hull penetration from sea ingress while supporting the propeller shaft and allowing rotation.',
    importance: 'Any defect in the shafting — cracked shaft, worn stern tube bearing, failed seal — can result in complete loss of propulsion or flooding. Propeller blade damage causes severe vibration which can structurally damage the hull, shafting, and main engine within minutes.',
    technical: 'The shaft line consists of the thrust shaft (transmitting axial thrust to the hull via the thrust block), intermediate shafts joined by rigid couplings, and the tail shaft passing through the stern tube. The stern tube is oil-lubricated with forward and aft lip seals. The propeller is a solid cast NiAlBronze fixed-pitch design, keyed and locked to the taper of the tail shaft.',
    components: ['Thrust shaft & Michell-type thrust block', 'Intermediate shafts (solid forged alloy steel)', 'Rigid flanged shaft couplings', 'Plummer block bearings (oil-lubricated)', 'Stern tube with forward and aft lip seals', 'Tail shaft (Aquamet stainless steel)', 'Fixed-pitch propeller (NiAlBronze — 4 or 5 blade)', 'Propeller key, locking nut and rope guard'],
    watchkeeping: ['Stern tube lube oil level — check header tank daily; any drop indicates seal leakage', 'Stern tube bearing temperature — monitor via IAS; max 70°C', 'Thrust block temperature — max 65°C', 'Intermediate shaft bearing temperatures — check each watch', 'Stern tube oil analysis — annual sample for water content', 'Propeller shaft vibration — investigate any sudden increase', 'Rope guard condition — inspect in port; ensure no fishing gear entangled']
  }
];
